version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - unused
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: log
              desc: use core.Logger (logrus via core adapter)
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
        - name: exported
        - name: if-return
        - name: early-return
        - name: line-length-limit
          arguments:
            - 140
        - name: import-shadowing
        - name: time-naming
        - name: increment-decrement
    wrapcheck:
      ignore-sig-regexps:
        - errors\.New\(
        - \*github\.com/netresearch/ofelia/core\.Context\)\.Next\(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
          - revive
          - wrapcheck
        path: _test\.go
      - linters:
          - nolintlint
        path: core/common\.go
        text: nolint:exhaustive
      - linters:
          - tagliatelle
        path: middlewares/slack\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netresearch/ofelia)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
