linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gofumpt
    - revive
    - gocyclo
    - ineffassign
    - errcheck
    - misspell
    - goconst
    - dupl
    - prealloc
    - typecheck
    - staticcheck
    - gosimple
    - govet
    - unused
    - unparam
    - nolintlint
    - predeclared
    - copyloopvar
    - exhaustive

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: blank-imports
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
      - name: exported
      - name: if-return
      - name: early-return
  misspell:
    locale: US
