linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - revive
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - revive

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: blank-imports
        disabled: true
      - name: package-comments
        disabled: true
