name: go test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Confirm Docker
        run: docker info

      - name: Vet
        run: go vet ./...

      - name: Format check
        run: |
          unformatted=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted:" >&2
            echo "$unformatted" >&2
            exit 1
          fi

      - name: Test
        run: go test ./...
